apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  labels:
    app: python-run
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-run
  template:
    metadata:
      labels:
        app: python-run

    spec: 
      containers:
      - name: docker-test
        image: docker_test
        imagePullPolicy: Never
        ports:
          - containerPort: 5000
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: python-run
  type: LoadBalancer